doco_cd_age_key: ENC[AES256_GCM,data:UJYK+k6v4SisClXoWo3FuFWUGHColRe5/7Q2SB5TSKW6PxqeqfQXKpGrNJWtGzYFcSv1M0G1/wMWCCOgkbffGJYEh2jcBDch4YsvPBeqMixT7yq/H/4OwfAF1fCH4AfKp4YhZSZHyhSbOZkZK1Nt9WyOkO8pMJdjUpMMGcS2hfIMH+Al5pSbYJy4JNVTHv0A2MVcnddy2sM9/clRXTCWkI8avBDXfhBKMt5EKf9447959ETsrs2qTaAsAtYJ,iv:rGZZYEAnYZydr6C3zyiCSkhGrkRCxx8X6JuKnx9pK7M=,tag:Ur34TWhLmojfKcYV/DOn8w==,type:str]
apprise_notify_urls: ENC[AES256_GCM,data:x2m4vjNaivl55L87TmV9hLNA/N2fWjNrOqHn7YPi5txuVTkGB46QletGtY5mzdiMh0wNhOEO+RRnIiyPB6IJ6wKa+F+fpbPeSitIAvMkweNZR1p35whWqq6/Pduq8YL0IdEw,iv:JO0P6T4XEiLNuQBEv12INyn3UGXt5M9TfjjB8K4GKrs=,tag:mb/ZrzLW75znuG0R3tHGyA==,type:str]
admin_user_password_hash: ENC[AES256_GCM,data:u2qHrtHD57TBuMRMnHPTSVjQSXlMp76+ULJaZdqZYifkagKixh0fN+LQVPq5HiYEDt4bUbqQP6yIJweyRi5U7pIIm8zoi2WviDGUjqDhzTAbmWXTqE+o5RIXs9KdVGy+8U38indANrWqn7KlLSLzb7Mq6pM0v5dT,iv:ZTQrm9qyX4mzbDrUJ/gNcDVT5U1ggK4bwjPQ7Pyf7EU=,tag:qIfhbNgQzpAuX5/cQjKDyg==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:8cXstshpdMhGzTTfQ31oEIDbK5nOJf4cVHMpuCu4az8IMVzyoWv0wzfT1WJGrNBVD6xAgZKuNRK3/fAjQw==,iv:8EmgV0I6Kb+e2FY92lm1qryEiq7ZDguMRu+8JeH7ENk=,tag:dVGEpuXfy2VUBOBKnktsSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuem5SN2VIbDl6cGxzNDVH
            RDNrUWQzWHZ3VWxGVWxHSlY2TWtmVURqNmdjCmk3dERwNXdHRnNUZ1paaVo2dS9u
            Wms1eEVpV3RLRjgvTHROV290U2ZUSzAKLS0tIE4wazhBTjJsVWlwbzlQaGdaZFZi
            N2ZuRmFzbWkzeFJlZkFYZEVwWG91OTgKHPrLlYUAN9Qrcz5Vfq1vTeLHWM+u1i/R
            6XylmTKYaV0CNGH1aWW9SBFT3NgfERrWjzJlkbUujCCsnO1iIz2p+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145yagqxlptxtw0jg3yawdqj6r6075l3svdakhhe6t7u4nfterg7qall256
    lastmodified: "2026-09-09T17:29:03Z"
    mac: ENC[AES256_GCM,data:ha0+x/gaP1Bj0SqLmu49hzQ3aT3usIToaQ+aucMYlxTrTGz2tMeHXT2yNrF+FucPXUsiqEYYJKl1staQS8ljmltt2iPdgkSiwbJgp4V9OAYaR5o/AvWAlI/z99RKl/CJNzrmh40ZsTMvYuMY1VsEIaLGwZ9aMAZukqkRQIWdXJs=,iv:v/MrgdOzJ7cVUNEnxNSQA93JeMzmLWkKx7HFh1iZIv0=,tag:pH8OUVyb78ihEwZuhCK6CA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
